### ISSUE TITLE
printDetails() no return

### ISSUE THREAD

**Issue by MiracelVip** [dparson55/NRFLite#11]
Hello,

first of all i want to say thank you for this great librarie! I just faced one problem... how to use the printDetails() function? I need it because i want to use  it together with an RPI.

The easyest way would be to port this librarie for the RPI but i think this will not happen :(

**Comment by dparson55** [comment]
Sorry it's not clear on how to use printDetails, I will put more information into an example.  To make printDetails work, you need to pass a serial object into the NRFLite constructor.  It can be a hardware or software serial object.  Below is an example:

```
#include <SPI.h>
#include <NRFLite.h>

NRFLite _radio(Serial); // Pass in a serial object here.

void setup()
{
    Serial.begin(115200);
    _radio.init(1, 9, 10); // Set this radio's Id = 1, along with its CE and CSN pins
    _radio.printDetails();
}

void loop()
{
}
```

There are other libraries that work with RPI but yeah, I probably will not port mine to it anytime soon.  I haven't needed an RPI for a project yet so don't have one to test with.
