### ISSUE TITLE
Name clash of STATUS with other libraries

### ISSUE THREAD

**Issue by arotyramel** [dparson55/NRFLite#16]
Hi Dave,

I had an issue using the NRFLite library together with another ESP8266 library (in particular the "[AlertMe](https://github.com/connornishijima/AlertMe)")

`nRF24L01.h:34:21: error: expected ',' or '...' before numeric constant`

In the nRF24L01.h header in line 34 there is a define for STATUS. This common name led to issues with the other lib. Therefore I have changed this line to:
#define STATUS_NRF      0x07
and replaced all occurences of STATUS with STATUS_NRF inside the NRFLite.cpp. 

I just wanted to mention this in case anyone else also has the same problem. 

Now it is working again like a charm. Thank you for the library :)

**Comment by dparson55** [comment]
Sorry for the trouble and thanks for the suggestion!  Fixed via bb59cf11c46bf524e7226e66e5ea1f0bd7ca0ae0
