### ISSUE TITLE
Power of transmission

### ISSUE THREAD

**Issue by hervema** [dparson55/NRFLite#22]
Hello, I'm using your library with success. However, I'm only asking you if there is a way to change , with your code, the power of transmission (min, low, high, max), or, perhaps, I'm wrong and that doesn't exist for this module ? Thanks in advance ! regards.

**Comment by dparson55** [comment]
Hi, please see https://github.com/dparson55/NRFLite/issues/12

**Comment by hervema** [comment]
Hello,

Didn’t see that ! sorry but thanks !

Regards,

Hervé

________________________________
De : Dave Parson <notifications@github.com>
Envoyé : Monday, April 22, 2019 2:18:00 AM
À : dparson55/NRFLite
Cc : hervema; Author
Objet : Re: [dparson55/NRFLite] Power of transmission (#22)


Hi, please see #12<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdparson55%2FNRFLite%2Fissues%2F12&data=02%7C01%7C%7C6232e350cfc34ab6724a08d6c6b7fa72%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636914890809177585&sdata=d8nPwDmY3hp6mEUMLrpMczuFX9S7CiJgsvoX1vz9NwM%3D&reserved=0>.

**Comment by dparson55** [comment]
Sure thing, good luck!
