### ISSUE TITLE
nrfLite with Arduino Due

### ISSUE THREAD

**Issue by AB624** [dparson55/NRFLite#33]
Marked as incompatible...Can you fix this issue ? regards

**Comment by dparson55** [comment]
I do not have a Due so would need your help to verify it's compatible.  Did you need to make any modifications to the Basic_RX or Basic_TX examples to make them work with the Due?  For example, someone asked me to add ESP8266 support and let me know they needed to use a special attribute for the RadioPacket struct, as shown in the Basic_RX_ESP8266 example.

**Comment by dparson55** [comment]
Closing since there's been no response.
