### ISSUE TITLE
ATTiny85 Sensor with 2 Pin

### ISSUE THREAD

**Issue by AlshainAvior** [dparson55/NRFLite#36]
Hi Dave,

This library (ATTiny85 with 2 Pin) is really help me a lot since tiny85 have limited IO, but is it possible to modify the library so the TX Mode can run in a two way communication (TX and RX using two pin for Attiny 85 --> **if we refer to basic TX with 2-pin and basic RX with 2-Pin in example**) ?

Thank you in advance

**Comment by dparson55** [comment]
The 2-pin operation supports two way communication, you can use the TwoWayCom_Software or TwoWayCom_Hardware examples as a starting point and just tweak them slightly to use the 2-pin init and rather than using Serial.print to see status, instead blink an led (for example).

**Comment by AlshainAvior** [comment]
Hi Dave,
It is run properly for the 2-Pin communication between Tiny85 and NRF24, but for two way communication (**Parsing/Sending String from TX <--> RX**) still not work, currently I using two unit arduino (uno) with NRF24 in each side and run deploy your Two way communication SW Based (TX and RX) it running properly, but once i tried to send the string it's not work properly (**TX Received [RX act as Transmitter]  multiple times and RX Received [TX act as Transmitter] sometimes or opposite**), by millis() it should be read per 3999ms , you can find the code in below 

https://github.com/AlshainAvior/NRFLITE-TEST/blob/master/Arduino_SWBased_TX/Arduino_SWBased_TX.ino

and

https://github.com/AlshainAvior/NRFLITE-TEST/blob/master/Arduino_SWBased_RX/Arduino_SWBased_RX.ino

Please help to take a look the code, I also mention about the packet data type (enum).
Thank you in advance

**Comment by dparson55** [comment]
I forked your example and got it working.  I created a [pull request](https://github.com/AlshainAvior/NRFLITE-TEST/pull/1) with the changes and put notes about the necessary changes.  Let me know if you have any questions.

![image](https://user-images.githubusercontent.com/19499747/76503153-90c89c80-6402-11ea-8005-09e2207e908c.png)

**Comment by AlshainAvior** [comment]
Hi Dave,

Big Thanks to you, it's work also in 1mbps, really appreciate your response and amazing library.

again, Thank you

**Comment by dparson55** [comment]
Good to hear it's working, best wishes!
