### ISSUE TITLE
How to increase output power with NRFLite library?

### ISSUE THREAD

**Issue by petitmouss** [dparson55/NRFLite#38]
Hi dparson55,

First of all, thanks for your contribution. A lot of time is saved by your involvement.
I've read https://lastminuteengineers.com/nrf24l01-arduino-wireless-communication/ and it seems that we can increase output power of the module. Maybe via a register but I don't find it.

Do you know how I can do that ?
Many thanks in advance, Bruno.

**Comment by dparson55** [comment]
Great article, thanks for sending it over.  NRFLite sets the radio to use its highest transmit power level and I have some additional detail in #12 about this decision.

The power is configured as part of the RF_SETUP register within `initRadio` in [NRFLite.cpp](https://github.com/dparson55/NRFLite/blob/master/src/NRFLite.cpp).
