### ISSUE TITLE
Good to know, use yield on ESP8266

### ISSUE THREAD

**Issue by petergullberg** [dparson55/NRFLite#42]
Great lib!
On an ESP8266, it need a yield function in the inner loop of NRFLite::printChannels()

#if defined(ESP8266)
            yield();
#endif

Cheers
\Peter

**Comment by dparson55** [comment]
How does this change look?
https://github.com/dparson55/NRFLite/compare/esp-yield

Unfortunately I don't have an ESP8266 to test so have to rely on anyone who reports an issue with them.

**Comment by petergullberg** [comment]
The ESP8266 WDT is ~1.5-3seconds, and your inner loop should be <100ms, so that should be fine

**Comment by dparson55** [comment]
I don't have an ESP but had so many requests to add their support that I just have to rely on helpful people like you to solve issues.  Thanks!
