### ISSUE TITLE
Set Power Level

### ISSUE THREAD

**Issue by jimann100** [dparson55/NRFLite#48]
Hi:

NRFLite seems to be more stable when driven by the ESP32 processor than standard nrf24 driver. Unfortunately, I can't find a way to change power levels on the higher powered ebyte transceivers. Is there one?

**Comment by dparson55** [comment]
Take a look at #12, hopefully it answers the question.

**Comment by jimann100** [comment]
Hi Dave:

After reviewing your code, I realized that you are setting output levels to 0dbm, which I believe are maximum level. #38 also points this out.

Love your code.

Jim

**Comment by dparson55** [comment]
Thanks, I'll go ahead and close this then.
