### ISSUE TITLE
correct definition for attinycore

### ISSUE THREAD

**Issue by marcolombardi-rm** [dparson55/NRFLite#5]
#if defined( __AVR_ATtiny84__ )
    #define USI_DI 6	// PB6
    #define USI_DO 5	// PB5
    #define SCK 4		// PB4
#elif defined( __AVR_ATtiny85__ )
    #define USI_DI 0	// PB0
    #define USI_DO 1	// PB1
    #define SCK 2		// PB2
#else
    #include <SPI.h> // Use the normal Arduino hardware SPI library if we are not on ATtiny.
#endif

**Comment by dparson55** [comment]
Sorry @marcolombardi-rm, this change does not compile with the library I'm officially supporting, the **attiny** library by David A. Mellis https://github.com/damellis/attiny  I tested with the Arduino IDE 1.8.5 and attiny 1.0.2.

**Comment by marcolombardi-rm** [comment]
https://github.com/SpenceKonde/ATTinyCore

Il 23/dic/2017 05:20, "dparson55" <notifications@github.com> ha scritto:
