### ISSUE TITLE
send text

### ISSUE THREAD

**Issue by roysG** [dparson55/NRFLite#59]
Hi,
Great library!

How can i send also text?

**Comment by dparson55** [comment]
There are two examples you can study on how to send text.

[Sensor_TX_ATtiny85_2Pin.ino](https://github.com/dparson55/NRFLite/blob/master/examples/Sensor_TX_ATtiny85_2Pin/Sensor_TX_ATtiny85_2Pin.ino#L73)
[Sensor_RX.ino](https://github.com/dparson55/NRFLite/blob/master/examples/Sensor_RX/Sensor_RX.ino#L133)
The radio hardware has a fairly small maximum packet size so for short strings of text, you can create a MessagePacket such as the one from this example.

[SplitDataAcrossMultiplePackets_TX.ino](https://github.com/dparson55/NRFLite/blob/master/examples/SplitDataAcrossMultiplePackets_TX/SplitDataAcrossMultiplePackets_TX.ino)
[SplitDataAcrossMultiplePackets_RX.ino](https://github.com/dparson55/NRFLite/blob/master/examples/SplitDataAcrossMultiplePackets_RX/SplitDataAcrossMultiplePackets_RX.ino)
For longer strings of text that will not fit into a single packet, you can study this example to see how one can split the text into smaller pieces that are later re-assembled into the long string of text after all the smaller packets are sent.

**Comment by roysG** [comment]
Thanks!
