### ISSUE TITLE
[Question] RadioID range

### ISSUE THREAD

**Issue by klerone** [dparson55/NRFLite#69]
Hello dear.

In the video I saw the range for the radioID is 0-255 or the network in the example sketch, but when I downloaded and open the examples this information is not there. I want to know if this is still valid or you removed the feature.

Long time ago I give up on this nRF24 radios because was difficult to make a network and I changed to the RFM69 from LowPowerLab, now I see your library is really easy to use and can fit inside the attiny, I will look for my old prototypes to give it a try.  
I have a project for my job to read the room temperature and other sensors and send back to the computer for control and data gatering, I want to use the nRF24 because it is cheap. 

thank you for sharing your library, amazing job.

**Comment by dparson55** [comment]
Thanks and yes the radio id range is 0-255.  I also had a [project where the nrf24's did not have enough range](https://www.youtube.com/watch?v=-fjxoaXwcc4&list=PLonofM-nQMBcdWDeKbQKqPqjwaciFnswa&index=6) so I used rfm69's and the LowPowerLab driver!  Hopefully the nrf24's work for your current project, they are really designed for high speed line of sight communication but sometimes they can work well when the distance and number of obstacles in the way isn't too much.  Good luck!
