### ISSUE TITLE
Servo jitters when receiving packet

### ISSUE THREAD

**Issue by dparson55** [dparson55/NRFLite#71]
From @mvoss96

I'm trying to control both a servo and and Esc from an Arduino nano who gets his commands from another Arduino nano using nrf24l01 radios.  I get the communication working perfectly now, however their seems to be some kind of interference between the nrflite and the servo library, because during receiving of messages the servo sometimes buzzes (and the esc drives the motor a little).  I'm guessing that something in the nrflite library blocks the timer1 that is used by the servo library to generate the servo signals.

Could that be the case?
And if yes is there any way to fix this behaviour so that the servo signal stays stable even while receiving messages?

**Comment by dparson55** [comment]
NRFLite temporarily disables the microcontroller's interrupts each time it communicates with the radio to prevent race conditions when using the interrupt features of the radio.  If Timer1 generates an interrupt while NRFLite has disabled them, it will delay the timer's interrupt handler and will mess up the timing of pulses going to the ESC and servo.  So here are a few things to try:

1. On the TX side, try performing a `NO_ACK` send shown below ([details in Basic_TX.ino](https://github.com/dparson55/NRFLite/blob/master/examples/Basic_TX/Basic_TX.ino#L66)).  On the RX side, when receiving one of these NO_ACK packets, the RX radio does not need to spend time sending back an acknowledgement packet and there's a chance this could improve the situation.
```
_radio.send(DESTINATION_RADIO_ID, &_radioData, sizeof(_radioData), NRFLite::NO_ACK)
```
2. If that doesn't help, try removing the disabling of interrupts by editing your local copy of `NRFLite.cpp` by commenting out the commands `noInterrupts();` and `interrupts();` in the [spiTransfer](https://github.com/dparson55/NRFLite/blob/master/src/NRFLite.cpp#L549) function.  This will break NRFLite functions when using the radio's IRQ pin for interrupt handling but is an easy change and maybe you won't use these functions in your projects.  If this does fix the problem and you are interested in improving your code, undo the changes you made to NRFLite.cpp and move on to option 3.
3. Optimize your RX code by using the interrupt features of NRFLite and the IRQ pin on the radio.  The [IRQ_RX.ino](https://github.com/dparson55/NRFLite/blob/master/examples/IRQ_RX/IRQ_RX.ino) example shows how to do this along with [this part of the NRFLite introduction video](https://youtu.be/tWEgvS7Sj-8?t=694).  Using an interrupt on the RX side will greatly reduce the amount of time NRFLite spends communicating with the radio, thereby reducing the amount of time the Timer1 interrupt is disabled.  When not using interrupts on the RX side, you are probably calling `hasData` during every iteration of your loop, and doing this wastes an enormous amount of time because each time it is called, NRFLite disables interrupts, communicates with the radio to see if any data was received, then re-enables interrupts.  If this happens during every iteration of the loop, this might be resulting in the Timer1 interrupt being disabled for the majority of the overall time.  This is the big advantage of using the interrupt feature of the radio, it allows the radio to signal the microcontroller that data was received and only then will NRFLite need to disable interrupts and read the data.

**Comment by dparson55** [comment]
@mvoss96 I'll go ahead and close this if I don't hear from you in the next couple of days.

**Comment by mvoss96** [comment]
Hi, thanks for your suggestions, but sadly even after commenting out the disableinterrupts the servo and esc still jitter when receiving packets. I guess there must be some interrupt used by nrflite that takes so long that the timer interrupt for the servo cant work properly. 
Interestingly i get the same behaviour with the wire.h library so i guess it is a widespread problem.
I solved it for me by connecting the servo and esc to a second arduino that communicates over uart (so no interrupts) with my main nano.

**Comment by dparson55** [comment]
Ok too bad, I took a quick look and see the SPI library disables interrupts when beginTransaction is called and re-enables them during endTransaction, so commenting them out in NRFLite is not enough.  If you're interested, you can try commenting out the call to `noInterrupts` in SPI.h in addition to commenting them out of NRFLite.

Example path: _arduino-1.8.12\hardware\arduino\avr\libraries\SPI\src\SPI.h_

![image](https://user-images.githubusercontent.com/19499747/139560346-e04380dd-b4e9-4d79-ad17-a22883914ef2.png)
