### ISSUE TITLE
It is not possible to change the full address of the device

### ISSUE THREAD

**Issue by DVK251** [dparson55/NRFLite#73]
Hi! Currently, the first 4 bytes of the device address are fixed and equal {1, 2, 3, 4} ( the fifth byte is the RadioId). In some cases, this may be inconvenient. I suggest setting the address in the private section of the class (just as it has already been done for the CONFIG_REG_SETTINGS_FOR_RX_MODE constant and others). 
```
private
    constexpr static uint8_t ADDRESS[4] = {1, 2, 3, 4}; // 1st 4 bytes of address (5th byte is RadioId)
```
and in procedure "initRadio" change `uint8_t address[5] = { 1, 2, 3, 4, radioId };` to `uint8_t address[5] = {ADDRESS[0], ADDRESS[1], ADDRESS[2], ADDRESS[3], radioId};`
and in procedure "prepForTx" change `uint8_t address[5] = { 1, 2, 3, 4, toRadioId };` to `uint8_t address[5] = {ADDRESS[0], ADDRESS[1], ADDRESS[2], ADDRESS[3], toRadioId};`

This will increase usability, but should not lead to an increase in the size of the code.

**Comment by dparson55** [comment]
Thanks for the suggestions and improvements!
