### ISSUE TITLE
TEST_RX has IRQ and CE swapped

### ISSUE THREAD

**Issue by Matszwe02** [dparson55/NRFLite#90]
1. Describe the bug:

swapped them, it starts to work again

2. Provide a short program that demonstrates the bug. DO NOT post your entire program, instead create a smaller version with no extraneous code: it should only include the logic necessary to reproduce the issue.

Examples -> Test_RX

```cpp
// TX code
```
TEST_TX
```
// TX code serial output
```
```cpp
// RX code
TEST_RX
```
```
// RX code serial output
cannot communicate when wires put at their labels, works well when swapped
```

**Comment by dparson55** [comment]
Figuring out the pins is always tough and the example pins might not match the mappings of your particular board, so it's expected that you might have to change them. The TEST_RX pins were setup for an Arduino UNO but you can change them as needed here
https://github.com/dparson55/NRFLite/blob/master/examples/Test_RX/Test_RX.ino#L17
and here
https://github.com/dparson55/NRFLite/blob/master/examples/Test_TX/Test_TX.ino#L23

CE is just the second parameter of `init` and internally is which ever pin the Arduino function `digitalWrite` uses.
https://github.com/dparson55/NRFLite/blob/master/examples/Test_RX/Test_RX.ino#L59

and IRQ is set to whatever pin on your microcontroller you've attached the interrupt to and is not associated with any library function. In the example, the Arduino function `digitalPinToInterrupt` looks up the interrupt number for the specified Arduino digital pin, and then `attachInterrupt` is utilized to run a function that you write to that interrupt number. So the library doesn't have any type of control of the interrupt pin, it's just Arduino functions and your particular board's Arduino pin mappings.
https://github.com/dparson55/NRFLite/blob/master/examples/Test_RX/Test_RX.ino#L147
